apiVersion: v1 
kind: Service 
metadata: 
  name: {{ .Values.fullname }} 
spec: 
  selector: 
    app: backend 
  ports: 
  - name: backend-port 
    protocol: TCP 
    port: 5000 
    targetPort: 5000 
  - name: db-port 
    protocol: TCP 
    port: 3306 
    targetPort: 3306 
  type: LoadBalancer
