apiVersion: v1 
kind: Service 
metadata: 
  name: {{ .Values.fullname }} 
spec: 
  selector: 
    app: frontend 
  ports: 
  - name: frontend-port 
    protocol: TCP 
    port: 80 
    targetPort: 80 
  type: LoadBalancer
