apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 976995869248.dkr.ecr.ap-south-1.amazonaws.com/shoewebapp:webappss-be
        ports:
        - containerPort: 5000
