apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 976995869248.dkr.ecr.ap-south-1.amazonaws.com/shoewebapp:webappss
        ports:
        - containerPort: 80
